server:
  port: 8091
  servlet:
    context-path: /policy

spring:
  kafka:
    bootstrap-servers: ${DBKK_CONNECTION:}:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 60000
            read-timeout: 120000
          file-service:
            url: ${FEIGN_FILE:}
            connect-timeout: 30000
            read-timeout: 60000
          user-service:
            url: ${FEIGN_USER:}
            connect-timeout: 30000
            read-timeout: 60000
  datasource:
    url: ${DBMS_CONNECTION:}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DBMS_USERNAME:}
    password: ${DBMS_PASSWORD:}
    hikari:
      connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
policy:
  auto-revoke:
    days: 30
    cron: "0 10 2 * * *"
    enabled: true
  service-auth:
    service-token: ${SERVICE_TOKEN:}        # nếu dùng Bearer token
